(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(auto-revert-check-vc-info t)
 '(auto-revert-interval 2)
 '(backward-delete-char-untabify-method 'hungry)
 '(blink-cursor-mode nil)
 '(c-basic-offset 4)
 '(company-auto-commit-chars '(32 95 40 41 119 46))
 '(company-dabbrev-downcase nil)
 '(company-idle-delay 0.8)
 '(company-require-match nil)
 '(company-selection-wrap-around t)
 '(company-tooltip-maximum-width 100)
 '(dabbrev-case-replace nil)
 '(default-input-method nil)
 '(delete-selection-mode t)
 '(display-time-day-and-date t)
 '(display-time-default-load-average nil)
 '(display-time-format "%a %H:%M")
 '(display-time-mode t)
 '(doom-modeline-buffer-file-name-style 'file-name)
 '(doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))
 '(doom-modeline-mode t)
 '(fast-but-imprecise-scrolling t)
 '(flycheck-disabled-checkers '(emacs-lisp-checkdoc))
 '(focus-follows-mouse nil)
 '(gc-cons-threshold 20000000)
 '(global-company-mode t)
 '(haskell-stylish-on-save t)
 '(highlight-indent-guides-method 'bitmap)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-major-mode 'text-mode)
 '(initial-scratch-message "")
 '(json-reformat:indent-width 2)
 '(lsp-log-io nil)
 '(lsp-restart 'interactive)
 '(lsp-signature-auto-activate nil)
 '(lsp-signature-render-documentation nil)
 '(lsp-sqls-server "~/Resoptima/sqls/sqls")
 '(lsp-ui-doc-delay 0.8)
 '(lsp-ui-doc-include-signature t)
 '(lsp-ui-doc-max-height 200)
 '(lsp-ui-doc-max-width 80)
 '(lsp-ui-doc-position 'bottom)
 '(magit-display-buffer-function 'magit-display-buffer-same-window-except-diff-v1)
 '(markdown-command "pandoc -f gfm")
 '(menu-bar-mode nil)
 '(package-selected-packages
   '(eglot-fsharp json-navigator emojify slime-volleyball minesweeper equake cyberpunk-2019-theme 2048-game company-terraform terraform-mode lsp-python-ms sly highlight-indent-guides-mode highlight-indent-guides rotate use-package tshell yasnippet-snippets rustic rustic-mode ron-mode treemacs lua-mode poke-line direnv slack osc vlf sclang-extensions gpastel nyan-mode minimap dmenu csharp-mode protobuf-mode cmake-mode melpa-upstream-visit ox-gfm sublimity } centered-cursor centered-cursor-mode yascroll tidal omnisharp magit-gerrit2 jinja2-mode magit-gerrit centaur-tabs yaml-mode dockerfile-mode anaconda-eldoc-mode jedi company-jedi elpy multiple-cursors markdown-preview-mode lsp-company all-the-icons lsp-elixir buffer-mode buffer-move winum js2-mode exwm which-key vterm-toggle exwm-config google lsp-treemacs lsp fsharp-mode flyspell-correct-ivy haskell-mode js2-refactor anaconda-mode perspective projectile flycheck counsel company ein vterm kaolin-themes monokai-theme monokai-pro-theme gruvbox-theme dante dante-mode company-lsp company-ghci lsp-haskell lsp-ui lsp-mode reverse-im company-nixos-options mood-line nord-theme treemacs-magit solaire-mode doom-modeline web-mode web-beautify undo-tree treemacs-projectile tide restclient rainbow-mode rainbow-delimiters pipenv persp-projectile nix-mode magit json-mode intero indium frames-only-mode exec-path-from-shell elm-mode doom-themes counsel-projectile company-web company-tern company-quickhelp company-anaconda auto-package-update))
 '(scroll-bar-mode nil)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(treemacs-follow-mode t)
 '(warning-suppress-types '((comp)))
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-sql-indent-offset 2)
 '(winum-scope 'frame-local))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ivy-current-match ((t (:extend t :background "dim gray"))))
 '(ivy-highlight-face ((t nil)))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#dc322f"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#859900"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#cb4b16"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#d33682"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#839496"))))
 '(yascroll:thumb-fringe ((t (:background "peru" :foreground "peru"))))
 '(yascroll:thumb-text-area ((t (:background "peru")))))
