(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(auto-revert-check-vc-info t)
 '(auto-revert-interval 2)
 '(auto-save-file-name-transforms '((".*" "/tmp/" t)))
 '(backup-directory-alist '((".*" . "/tmp/")))
 '(backward-delete-char-untabify-method 'hungry)
 '(blink-cursor-mode nil)
 '(company-dabbrev-downcase nil)
 '(company-idle-delay 0.8)
 '(company-insertion-triggers '(32 95 40 41 119 46))
 '(company-require-match nil)
 '(company-selection-wrap-around t)
 '(company-tooltip-maximum-width 100)
 '(custom-safe-themes
   '("370109bfd8c7784bbf62e3f8c4f332aed0b915116e2d718bc7e2b8e0ebe35e10" default))
 '(dabbrev-case-replace nil)
 '(dashboard-startup-banner 'logo)
 '(default-input-method nil)
 '(delete-selection-mode t)
 '(eglot-fsharp-server-verbose 1)
 '(flycheck-disabled-checkers '(emacs-lisp-checkdoc))
 '(gc-cons-threshold 20000000)
 '(haskell-stylish-on-save t)
 '(highlight-indent-guides-method 'bitmap)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-major-mode 'text-mode)
 '(initial-scratch-message "")
 '(json-reformat:indent-width 2)
 '(lsp-diagnostics-disabled-modes '(*))
 '(lsp-lens-place-position 'above-line)
 '(lsp-restart 'interactive t)
 '(lsp-signature-auto-activate nil)
 '(lsp-signature-render-documentation nil)
 '(magit-display-buffer-function 'magit-display-buffer-same-window-except-diff-v1)
 '(markdown-command "pandoc -f gfm")
 '(menu-bar-mode nil)
 '(package-selected-packages
   '(lsp-pyright yasnippet yaml-mode winum which-key vterm-toggle undo-tree rotate restclient rainbow-mode rainbow-delimiters protobuf-mode multiple-cursors mood-one-theme mood-line markdown-preview-mode magit lsp-mode jinja2-mode howdoyou highlight-indent-guides hcl-mode gpastel fsharp-mode format-all flyspell-correct-ivy flycheck exec-path-from-shell emojify dumb-jump dockerfile-mode direnv dashboard counsel-projectile company-quickhelp cmake-mode buffer-move auto-package-update))
 '(scroll-bar-mode nil)
 '(tab-bar-mode nil)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(undo-tree-history-directory-alist '(("." . "~/.emacs.d/.undo-tree")))
 '(warning-suppress-log-types '((lsp-mode) (lsp-mode) (comp)))
 '(warning-suppress-types '((lsp-mode) (comp)))
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-sql-indent-offset 2)
 '(winum-scope 'frame-local))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ivy-current-match ((t nil)))
 '(ivy-highlight-face ((t nil)))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "plum1"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#859900"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#cb4b16"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#d33682"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#839496"))))
 '(yascroll:thumb-fringe ((t (:background "peru" :foreground "peru"))))
 '(yascroll:thumb-text-area ((t (:background "peru")))))
